version: '3.1'

services:
  worldmaker:
    image: node:16.16.0-alpine
    restart: always
    ports:
      - 8080:80
      - 4343:443
    volumes:
      - type: bind
        source: ./src
        target: /srv